### ISSUE TITLE
SampleController class is not compiling

### ISSUE THREAD

**Issue by Anubhav2201** [ReneRanzinger/IFEDS-backend#22] opened 2019-11-23 12:49 UTC
-Not able to find java.lang.module for ResolutionException.
Please update the code.

**Comment by akshaykokane** [comment] 2019-11-23 14:58
WIP

**Comment by akshaykokane** [comment] 2019-11-23 15:03
java.lang.module for ResolutionException.

JAVA 9 required for the above class. 

@ReneRanzinger can you help to know which Java Version we should use?

**Comment by ReneRanzinger** [comment] 2019-11-23 18:31
If there is no reason preventing it why not go to 11. For 13 I am not sure we will have support for it on the server.

**Comment by ReneRanzinger** [comment] 2019-11-23 18:35
But why do you use ResolutionException? Are you using it yourself or does it come from the Framework? If the first, why not create your own Exception class and not have to worry about it.

**Comment by akshaykokane** [comment] 2019-11-23 19:36
- I guess the problem is with SpringBoot 2.0. They have implemented.  Optional findOne(Example example) . earlier it was just <T> findOne(Example example). findById() returns the object if the id is present else return type is optional.I have replaced the code with null and try to resolve the issue. @Anubhav2201  please check now. I am closing the ticket. Feel free to open again if the error persists. Thank you.
- 
- More info : (https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html?is-external=true
- )

**Closed as completed by akshaykokane** 2019-11-23 19:36 UTC

**Comment by Anubhav2201** [comment] 2019-11-25 08:27
@akshaykokane Thank you. It is working now.
